<a href="https://colab.research.google.com/github/WhiteWolf088/Practice/blob/main/Tennsorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this note book, we are going to cover some of the most fundamental concepts of tensors using TensorFlow
More specifically,We are going to cover:
  * Introduction to tensors
  * Getting information from tensors
  * Manipulating tensors
  * Tensors and Numpy
  * Using @tf.function(a way to speed up your regular Python functions)
  * Using GPU with TensorFlow (or TPUs )
  * Exercises to try for Yourself!



# Introduction to Tensors

In [ ]:
#Import TennsorFlow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [ ]:
#creatin tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#heck the numbwr of dimensions
scalar.ndim

0

In [ ]:
#create vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#chck the dimension of a vector
vector.ndim

1

In [ ]:
#create Matrix
matrix=tf.constant([[7,9],
                    [9,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 9],
       [9, 7]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix=tf.constant([[7,9],
                           [6,8],
                           [5.,4]])
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[7., 9.],
       [6., 8.],
       [5., 4.]], dtype=float32)>

In [ ]:
another_matrix.ndim

2

In [ ]:
tensor=tf.constant([[[1,4,7],
                   [2,5,8]],
                  [[4,8,6],
                   [3,6,9]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 4, 7],
        [2, 5, 8]],

       [[4, 8, 6],
        [3, 6, 9]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# tf.Variable

In [ ]:
changeble_tensor=tf.Variable([7,9])
unchangeble_tensor=tf.constant([7,9])
changeble_tensor,unchangeble_tensor
changeble_tensor[0].assign(9)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([9, 9], dtype=int32)>

In [ ]:
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
not_shuffled=tf.constant([[7,8,9],
                          [4,5,6],
                          [1,2,3]])
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled,seed=55)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]], dtype=int32)>

In [ ]:

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
tf.zeros([7,6])

<tf.Tensor: shape=(7, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.ones(shape=(7,6))

<tf.Tensor: shape=(7, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

#x=tf.contant(some_matrix)
#y=tf.constant(vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
a=tf.constant(numpy_A)

In [ ]:
a

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
a=tf.constant(numpy_A,shape=(3,8))
a

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [ ]:
a.ndim

2

In [ ]:
rank_4_tensor= tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
print("NNumber of element in the tensor : ",tf.size(rank_4_tensor).numpy())

NNumber of element in the tensor :  120


In [ ]:
print("the Number of dimensions in a tensor : ",rank_4_tensor.ndim)

the Number of dimensions in a tensor :  4


In [ ]:
print("The Shape of the tensor is : ",rank_4_tensor.shape)

The Shape of the tensor is :  (2, 3, 4, 5)


In [ ]:
print("The type of the tensor : ",rank_4_tensor.dtype)

The type of the tensor :  <dtype: 'float32'>


### Indexing tensors

Tensors can be indexed just like Python lists. 

In [ ]:
rank_2_tensor=tf.constant([[7,9],
                           [4,5]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 9],
       [4, 5]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=-1)


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[7],
        [9]],

       [[4],
        [5]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[7, 9]],

       [[4, 5]]], dtype=int32)>

###Manipulating Tensors

**Basic Operators**

`+`, `-`, `*`, `/`

In [ ]:
tensor=tf.constant([[10,7],
                    [7,9]])
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-3, -1]], dtype=int32)>

In [ ]:
tensor=tf.constant([[7,9],
                    [5,6]])
tensor*8

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[56, 72],
       [40, 48]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 9],
       [5, 6]], dtype=int32)>

In [ ]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 19],
       [15, 16]], dtype=int32)>

In [ ]:
tf.subtract(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-3, -1],
       [-5, -4]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 9],
       [5, 6]], dtype=int32)>

###Matrix Multiplixation

In Machine Learning, Matrix multiplication is one of the most common tensor operations.

There are two rules our tensors(or matrices) need to fulfil if we are going to matrix multiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of the innner dimensions

In [ ]:
 matrix1=tf.constant([[1,2],
                      [7,2],
                      [2,5]])
 matrix1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [7, 2],
       [2, 5]], dtype=int32)>

In [ ]:
matrix2=tf.constant([[3,5,8],
                     [6,7,5],
                     [1,8,4]])
matrix2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 5, 8],
       [6, 7, 5],
       [1, 8, 4]], dtype=int32)>

In [ ]:
tf.matmul(matrix2,matrix1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[54, 56],
       [65, 51],
       [65, 38]], dtype=int32)>

In [ ]:
x=tf.constant([[2,3],
               [4,5],
               [7,8]])
y=tf.constant([[3,2],
               [6,5],
               [9,8]])
print(x)
print(y)

tf.Tensor(
[[2 3]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[3 2]
 [6 5]
 [9 8]], shape=(3, 2), dtype=int32)


In [ ]:
tf.reshape(x,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [5, 7, 8]], dtype=int32)>

In [ ]:
tf.matmul(tf.reshape(x,shape=(2,3)),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 60,  51],
       [129, 109]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 93,  80],
       [111,  95]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplcation using:
* `tf.matmul()`
* `tf.tensordot()`
* `@`


In [ ]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 3],
        [4, 5],
        [7, 8]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 2],
        [6, 5],
        [9, 8]], dtype=int32)>)

In [ ]:
tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 93,  80],
       [111,  95]], dtype=int32)>

Generally, When performing matrix multiplication on two tensors and one of the axes does not line up,you will transpose(rather than reshape) one of the tensors to satisfy the matrix multiplication rules.

###Changing datatype of a Tensor

In [ ]:
#create a new tensor with default(float 32)
a=tf.constant(7,8)
a,a.dtype

(<tf.Tensor: shape=(), dtype=complex64, numpy=(7+0j)>, tf.complex64)

In [ ]:
b=tf.cast(a,dtype=tf.int32)
b

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
b=tf.constant([7,9])
b,b.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 9], dtype=int32)>,
 tf.int32)

In [ ]:
c=tf.cast(b,dtype=tf.int16)
c,c.dtype

(<tf.Tensor: shape=(2,), dtype=int16, numpy=array([7, 9], dtype=int16)>,
 tf.int16)

In [ ]:
450000/12

37500.0

In [ ]:
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqd=tf.cast(b,dtype=tf.complex64)
d,d.dtype

(<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([7.+0.j, 9.+0.j], dtype=complex64)>,
 tf.complex64)

### Aggregating Tensors

Aggregating Tensors = condensing them from multiplke values down to a smaller amount of Values

In [ ]:
P=tf.constant([-7,-9])
P

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, -9], dtype=int32)>

In [ ]:
tf.abs(P)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 9], dtype=int32)>

Let's go through the following forms of aggregation 

* Get the minimum
* Get the Maximum
* Get the mean of the tensor
* Get the sum of a Tensor

In [ ]:
A=tf.constant([[7,9],[4,5]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 9],
       [4, 5]], dtype=int32)>

In [ ]:
print(tf.reduce_mean(A))

tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
tf.reduce_min(A)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
tf.reduce_max(A)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
tf.reduce_sum(A)

<tf.Tensor: shape=(), dtype=int32, numpy=25>

In [ ]:
B=tf.constant([[1,2],[6,3]])
B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [6, 3]], dtype=int32)>

In [ ]:
tf.add(A,B)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8, 11],
       [10,  8]], dtype=int32)>

In [ ]:
tf.matmul(A,B)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[61, 41],
       [34, 23]], dtype=int32)>

In [ ]:
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 6, 34, 12,  2, 48, 84, 40, 18, 66, 11, 36, 16, 84, 43, 83, 68, 23,
       98, 39,  6, 82, 67, 90,  3, 40, 36, 26, 19, 82, 22, 97, 59, 49, 13,
       63, 20, 66, 81, 85,  0,  6, 59, 43, 38,  2, 67, 35, 72, 53, 46])>

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
tf.reduce_max(E).numpy()

98

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=44>

In [ ]:
tf.reduce_sum(E).numpy()

2238

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=833>

In [ ]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.864899>

In [ ]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=833.1824>

### Find the Positional Maximum and Minimum of a tensor

In [ ]:
tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=17>

In [ ]:
tf.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=39>

In [ ]:
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.math.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.math.reduce_max(F)==F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
tf.math.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
tf.math.reduce_min(F)==F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a Tensor(removing all single dimensions)

In [ ]:
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G_squeezes=tf.squeeze(G)
G_squeezes

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One-hot encoding Tensor

In [ ]:
some_list=([1,2,3,4,5])
some_list

[1, 2, 3, 4, 5]

In [ ]:
tf.one_hot(some_list,depth=10)

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list,depth=5,on_value="Police",off_value="Reddy")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'Reddy', b'Police', b'Reddy', b'Reddy', b'Reddy'],
       [b'Reddy', b'Reddy', b'Police', b'Reddy', b'Reddy'],
       [b'Reddy', b'Reddy', b'Reddy', b'Police', b'Reddy'],
       [b'Reddy', b'Reddy', b'Reddy', b'Reddy', b'Police'],
       [b'Reddy', b'Reddy', b'Reddy', b'Reddy', b'Reddy']], dtype=object)>

### Squaring, log, Square root

In [ ]:
H=tf.range(10)
H

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.        , 0.99999994, 1.4142134 , 1.7320508 , 1.9999999 ,
       2.236068  , 2.4494896 , 2.6457512 , 2.828427  , 3.        ],
      dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([     -inf, 0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 ,
       1.7917595, 1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

* TensorFlow interact beautifully with Numpy arrays.

In [ ]:
j=tf.constant(np.array([1.,2.,3.,4.,8.,7]))
j

<tf.Tensor: shape=(6,), dtype=float64, numpy=array([1., 2., 3., 4., 8., 7.])>

In [ ]:
np.array(j),type(np.array(j))

(array([1., 2., 3., 4., 8., 7.]), numpy.ndarray)